spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: bookshop
          uri: lb://bookshop
          predicates:
            - Path=/bookshop/**
        - id: exchange
          uri: lb://exchange
          predicates:
            - Path=/**
      default-filters:
        - name: Retry
          args:
            retires: 3
            methods: GET,POST,PUT,DELETE
            statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

resilience4j.circuitbreaker:
  instances:
    bookshop:
      registerHealthIndicator: true
      slidingWindowSize: 20
    exchange:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate