spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: bookshop
          uri: lb://BOOKSHOP
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookshopCircuitBreaker
                fallbackUri: forward:/fallback

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    gateway:
      enabled: true
    