logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.web.client: DEBUG

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: bookshop
          uri: lb://bookshop
          predicates:
            - Path=/bookshop/**
        - id: exchange
          uri: lb://exchange
          predicates:
            - Path=/**
      default-filters:
        - name: Retry
          args:
            retires: 3
            methods: GET,POST,PUT
            statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'