eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/bookshop
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  circuitbreaker:
    instances:
      exchanges:
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5 
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 2 
  retry:
    instances:
      exchangesRetry:
        maxAttempts: 3
        waitDuration: 1000ms
  ratelimiter:
    instances:
      exchange:
        timeoutDuration: 1000ms
        limitRefereshPeriod: 5000
        limitForPeriod: 5