eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234567
    url: jdbc:postgresql://localhost:5432/bookshop
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  circuitbreaker:
    instances:
      exchanges:
        slidingWindowSize: 10  # Tamanho da janela de monitoramento
        failureRateThreshold: 50  # Porcentagem de falhas para abrir o CircuitBreaker
        minimumNumberOfCalls: 5  # Número mínimo de chamadas antes de avaliar o status
        waitDurationInOpenState: 10000ms  # Tempo que ele fica aberto antes de tentar reabrir
        permittedNumberOfCallsInHalfOpenState: 2  # Número de chamadas permitidas no meio aberto
  retry:
    instances:
      exchangesRetry:
        maxAttempts: 3  # Número máximo de tentativas antes de falhar
        waitDuration: 1000ms  # Tempo de espera entre tentativas