eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234567
    url: jdbc:postgresql://localhost:5432/bookshop
  jpa:
    hibernate:
      ddl-auto: update